### ISSUE TITLE
Solution for having msg notifications as JS popups

### ISSUE THREAD

**Issue by neilyoung** [mikestefanello/pagoda#96]
I have added this as an unobtrusive alternative to the server-side rendered notifications to my project and would like to share details (for validation and discussion), in case you are interested. Just in case.

<img width="1601" alt="Image" src="https://github.com/user-attachments/assets/0ca30dbe-7278-420c-947a-ec0a6fd8a6b7" />

**Comment by neilyoung** [comment]
Noticed right now that the welcome text is pretty nonsense :)

**Comment by mikestefanello** [comment]
How are you implementing those?

Curious to what you're using for CSS. I tried upgrading Bulma to 1.x but got frustrated with how it was coming out so I started looking at alternatives (again).

**Comment by neilyoung** [comment]
OK, I hope you'll find it not too clumsy. I also don't want to bother with PRs, so it's just a gist. It took me a while and needed tons of different approaches but this one is working fine now under all circumstances.

1) I decided to use [JS SnackBar](https://www.michaelmickelson.com/js-snackbar/) for the notification. I was using it with React years ago and it's working reliably and allows for message stacking and auto-disposal.

2) I downloaded the latest scripts from there (CSS min and JS min) and put it into my static folder, injected in `core.gohtml`, into the `{{ define "js" }}` template (well the css should better go to css, but that's marginal):

```js
    <!-- JS-Snackbar CSS and Script -->
    <link rel="stylesheet" href="/static/js-snackbar.min.css" />
    <script src="/static/js-snackbar.min.js"></script>    
    
    <!-- The message div holding an array of JSON objects -->
    <div id="snackbarMessages" style="display: none;"></div>
```

3) `snackbarMessages` is the central div and is updated whenever some server-side-code saves a message to the flash cookie from GO code, like:

```go
	msg.Success(ctx, "Hello World")
```

4) `messages.gohtml` is simply this now. The `.Context` comes from the `.Page`:

```go
{{ define "messages" }}
    <script>
        document.getElementById('snackbarMessages').innerHTML = '{{ getMessages .Context }}';
    </script>
{{ end }}
```

5) I'm fetching the messages from the flash cookie in GO code and provide this function in `funcmap.go` down to the templates:

```
	funcs["getMessages"] = func(ctx echo.Context) template.HTML {
		successMessages := msg.Get(ctx, "success")
		infoMessages := msg.Get(ctx, "info")
		warningMessages := msg.Get(ctx, "warning")
		dangerMessages := msg.Get(ctx, "danger")

		var allMessages []map[string]string

		// Assemble all messages
		allMessages = append(allMessages, formatMessages("success", successMessages)...)
		allMessages = append(allMessages, formatMessages("info", infoMessages)...)
		allMessages = append(allMessages, formatMessages("warning", warningMessages)...)
		allMessages = append(allMessages, formatMessages("danger", dangerMessages)...)

		if len(allMessages) == 0 {
			allMessages = []map[string]string{} // Return empty array instead of null
		}

		// JSON-Nachrichten erzeugen
		jsonMessages, err := json.Marshal(allMessages)
		if err != nil {
			log.Ctx(ctx).Error("Error while converting messages to JSON", "error", err)
			return template.HTML("[]") // Return empty array
		}

		log.Ctx(ctx).Debug("getMessages", "jsonMessages", string(jsonMessages))
		return template.HTML(string(jsonMessages))
	}

```

With this little helper:

```go
// Helper format messages to JSON array of objects
func formatMessages(msgType string, messages []string) []map[string]string {
	var formattedMessages []map[string]string

	for _, msg := range messages {
		formattedMessages = append(formattedMessages, map[string]string{
			"type": msgType, // Message type (e.g. "success", "info", etc.)
			"text": msg,     // The message
		})
	}
	return formattedMessages
}
```

6) The observer for the `snackMessage` div and the `SnackBar` display, also put into the `{{ define "js" }}` template in `core.gohtml`. Here I'm a bit in doubt if I shouldn't wait for the `DOMContentLoaded` event to instantiate the watcher and I'm also not sure, if this code leaks.

```js
    <script>
        function showSnackbar() {
            // Get formatted JSON from the `snackBarMessages` div
            const messagesDiv = document.getElementById('snackbarMessages');
            if (!messagesDiv) return; 

            let messages;
            try {
                messages = JSON.parse(messagesDiv.innerText);
                // Display
                messages.forEach(function (msg) {
                    window.SnackBar({
                        message: msg.text,
                        status: msg.type,
                    });
                });
            } catch (error) {
                console.error('Error while processing snackbarMessages JSON:', error);
            }
        }

        // Observes changes in the `snackbarMessages` div
        function watchSnackbarMessages() {
            let targetNode = document.getElementById('snackbarMessages');
            if (!targetNode) return;

            let observer = new MutationObserver(() => {
                showSnackbar(); // Display the SnackBar
            });

            // Launch observer
            observer.observe(targetNode, { childList: true, subtree: true });
        }

        // Launch watcher
        watchSnackbarMessages();
    </script>

```

7) Whether you add this extra glue styles to your `styles.css` is optional. I was just using it to make emphasized text better visible in especially dark mode and to align the div to be initally starting it's appearance from the top of the `footer`.

```css
    <style>
        .js-snackbar__message {
            color: #fff; /* White for all the text */
        }

        .js-snackbar__message strong {
            color: #ffd700; /* Strong needs another colour in dark mode */
        }

        .js-snackbar__wrapper {
            text-align: left; /* Left aligned texts (matter of taste) */
        }
        .js-snackbar-container {
            position: fixed !important;
            bottom: calc(50px + env(safe-area-inset-bottom)) !important; /* A little dynamic distance to the footer  */
            left: 0 !important;
            width: 100% !important;
            max-width: 100% !important;
            text-align: center !important;
            z-index: 1000 !important; /* Has to be on top of all */
        }
    </style>

```
Of course, since I'm lazy I also put it into `core.gohtml`,`{{ define "css" }}` template :)

Feel free to give it a try or put it aside if it doesn't fit your roadmap. 

CU
